WebFormL1/Models/Province.cs
namespace WebFormL1.Models
{
    public class Province
    {
        public Province()
        {
        }
        public Province(int id, string? name,string? level)
        {
            Id = id;
            Name = name;
            Level = level;
        }
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Level { get; set; }
        public ICollection<District>? Districts { get; set; }
    }
}

WebFormL1/Controllers/ProvincesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebFormL1.BusinessLogic;
using WebFormL1.EditModel;
using WebFormL1.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;
using WebFormL1.Constant;
using WebFormL1.Interface;
using WebFormL1.Utility;

namespace WebFormL1.Controllers
{
    public class ProvincesController : BaseController
    {
        private readonly IProvinceBL _bl;

        public ProvincesController(IProvinceBL bl)
        {
            _bl = bl;
        }


        // GET: Provinces
        public IActionResult Index(int? page,int? size,string searchString = "")
        {
            int pageIndex = Validate.ValidatePageNumber(ref page);
            int pageSize = Validate.ValidatePageSize(ref size);
            ViewBag.size = GetPageSizeOptions(size);
            ViewBag.currentSize = size;
            var provincesViewModel = _bl.FetchProvincePage(pageIndex, pageSize, searchString);
            ViewData["searchString"] = searchString;
            return View(new StaticPagedList<ProvinceViewModel>(provincesViewModel.ViewModel!,
                                     pageIndex, pageSize, provincesViewModel.TotalPages));
        }
        // GET: Provinces/Create
        public IActionResult Create()
        {
            var levels = new List<SelectListItem>
            {
                new SelectListItem { Value = "Thành phố trung ương", Text = "Thành phố trung ương" },
                new SelectListItem { Value = "Tỉnh", Text = "Tỉnh" }
            };
            ViewBag.Levels = levels;
            return View();
        }

        // POST: Provinces/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Level")] ProvinceEditModel provinceEditModel)
        {
            var levels = new List<SelectListItem>
            {
                new SelectListItem { Value = "Thành phố trung ương", Text = "Thành phố trung ương" },
                new SelectListItem { Value = "Tỉnh", Text = "Tỉnh" }
            };
            if (!ModelState.IsValid)
            {
                ViewBag.Levels = levels;
                return View(provinceEditModel);
            }

            var isSucessCreating = await _bl.AddProvince(provinceEditModel);
            if(!isSucessCreating)
            {
                TempData["ErrorMessage"] = "An error occurred while creating the province.";
                return View(provinceEditModel);
            }    


            TempData["SuccessMessage"] = "Province created successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Provinces/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var province = await _bl.GetProvinceById(id);

            if (province == null)
            {
                return NotFound();
            }
            var levels = new List<SelectListItem>
            {
                new SelectListItem { Value = "Thành phố trung ương", Text = "Thành phố trung ương" },
                new SelectListItem { Value = "Tỉnh", Text = "Tỉnh" }
            };
            ViewBag.Levels = levels;
            var provinceEditModel = new ProvinceEditModel(province.Id, province.Name, province.Level);
            return View(provinceEditModel);
        }

        // POST: Provinces/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, ProvinceEditModel provinceEditModel)
        {
            var levels = new List<SelectListItem>
            {
                new SelectListItem { Value = "Thành phố trung ương", Text = "Thành phố trung ương" },
                new SelectListItem { Value = "Tỉnh", Text = "Tỉnh" }
            }; 
            if (id != provinceEditModel.Id)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                ViewBag.Levels = levels;
                return View(provinceEditModel);
            }

            var isSucessEdit = await _bl.EditProvince(provinceEditModel);
            if(!isSucessEdit)
            {
                TempData["ErrorMessage"] = "An error occurred while updating the province.";
                return View(provinceEditModel);
            }    
            TempData["SuccessMessage"] = "Province created successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Provinces/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var province = await _bl.GetProvinceById(id);

            if (province == null)
            {
                return NotFound();
            }

            var provinceViewModel = new ProvinceViewModel(province.Id, province.Name, province.Level);
            return View(provinceViewModel);
        }

        // POST: Provinces/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var province = await _bl.GetProvinceById(id);
            if (province == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var isSucessDelete = await _bl.DeleteProvince(province);
            if(!isSucessDelete)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the province.";
                return RedirectToAction(nameof(Index));
            }

            TempData["SuccessMessage"] = "Province deleted successfully";
            return RedirectToAction(nameof(Index));
        }
    }
}

WebFormL1/Views/Provinces/Create.cshtml
@model WebFormL1.EditModel.ProvinceEditModel

@{
    ViewData["Title"] = "Create";
}

<h1>Thêm tỉnh/thành phố</h1>
<hr />
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="Level" class="control-label"></label>
                <select asp-for="Level" asp-items="ViewBag.levels" class="form-control">
                    <option value="">Chọn cấp bậc</option>
                </select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách tỉnh/thành phố</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebFormL1/Views/Provinces/Delete.cshtml
@model WebFormL1.ViewModel.ProvinceViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa thông tin</h1>

<h3>Bạn có chắc muốn xóa thông tin tỉnh/thành phố này?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Danh sách tỉnh/thành phố</a>
    </form>
</div>

WebFormL1/Views/Provinces/Edit.cshtml
@model WebFormL1.EditModel.ProvinceEditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa thông tin Tỉnh</h1>
<hr />
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-md-3">
                <label asp-for="Level" class="control-label"></label>
                <select asp-for="Level" asp-items="ViewBag.levels" class="form-control">
                    <option value="">Chọn cấp bậc</option>
                </select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Lưu" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách tỉnh/thành phố</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebFormL1/Views/Provinces/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<WebFormL1.ViewModel.ProvinceViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách tỉnh/thành phố</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Thêm mới</a>
</p>
<div class="position-absolute end-0 top-0">
    <!-- Search form with Bootstrap styles -->
    <form asp-action="Index" method="get" class="form-inline">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Tìm.." name="searchString" value="@ViewBag.searchString">
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">
                    <i class="fa fa-search" aria-hidden="true"></i> Tìm
                </button>
            </div>
        </div>
    </form>
</div>


@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Level)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Level)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Sửa</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row">
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Html.BeginForm("Index", "Provinces", FormMethod.Get))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
            </p>
            @Html.Hidden("searchString", (object)ViewBag.searchString)
        }
    </div>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
        Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
</div>
@{
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }
        if (request.Query[key].Count > 1)
        {
            foreach (var item in (string[])request.Query[key])
            {
                urlTemplate += "&" + key + "=" + item;
            }
        }
        else
        {
            urlTemplate += "&" + key + "=" + request.Query[key];
        }
    }

    var startIndex = Math.Max(Model.PageNumber - 5, 1);
    var finishIndex = Math.Min(Model.PageNumber + 5, Model.PageCount);
}

@if (Model.PageCount > 1)
{
    <ul class="pagination">
        @if (Model.PageNumber != startIndex)
        {
            <li class="page-item">
                <a class="page-link" title="1" href="@urlTemplate.Replace("{0}", "1")">Đầu</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", (Model.PageNumber-1).ToString())">Trước</a>
            </li>
        }
        @for (var i = startIndex; i <= finishIndex; i++)
        {
            if (i == Model.PageNumber)
            {
                <li class="page-item active">
                    <a class="page-link" href="#">@i <span class="sr-only">(current)</span></a>
                </li>
            }
            else
            {
                <li class="page-item"><a class="page-link" title="Trang @i.ToString()" href="@urlTemplate.Replace("{0}", i.ToString())">@i</a></li>
            }
        }
        @if (Model.PageNumber != finishIndex)
        {
            <li class="page-item">
                <a class="page-link" title="@Model.PageCount.ToString()" href="@urlTemplate.Replace("{0}", (Model.PageNumber+1).ToString())">Sau</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", Model.PageCount.ToString())">Cuối</a>
            </li>
        }
    </ul>
}