WebFormL1/Models/Employee.cs
using System.ComponentModel.DataAnnotations;

namespace WebFormL1.Models
{
    public class Employee
    {
        public Employee(int id, string? name, DateTime dateOfBirth,  int ethnicId,
                                    int jobId, string? identityCardNumber, string? phoneNumber, int? provinceId,
                                    int? districtId, int? communeId)
        {
            Id = id;
            Name = name;
            DateOfBirth = dateOfBirth;
            EthnicId = ethnicId;
            JobId = jobId;
            IdentityCardNumber = identityCardNumber;
            PhoneNumber = phoneNumber;
            ProvinceId = provinceId;
            DistrictId = districtId;
            CommuneId = communeId;
        }
        public Employee()
        { 
        }  
        public int Id { get; set; }
        public string? Name { get; set; }
        [DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        public int JobId { get; set; }
        public int EthnicId { get; set; }
        public string? IdentityCardNumber { get; set; }
        public string? PhoneNumber { get; set; }
        public int? ProvinceId { get; set; }
        public int? DistrictId { get; set; }
        public int? CommuneId { get; set; }
        public int? DepartmentId { get; set; }
        public virtual District? District { get; set; }
        public virtual Job? Job { get; set; }
        public virtual Ethnic? Ethnic { get; set; }
        public virtual Commune? Commune { get; set; }
        public virtual Province? Province { get; set; }
        public virtual List<Degree>? Degrees { get; set; }
        public virtual Department? Department { get; set; }
    }
}

WebFormL1/Controllers/DegreesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebFormL1.BusinessLogic;
using WebFormL1.EditModel;
using WebFormL1.Interface;
using WebFormL1.Service;
using WebFormL1.ViewModel;

namespace WebFormL1.Controllers
{
    public class DegreesController : Controller
    {
        readonly int MaxNumberOfDegrees = 3;
        private readonly RepositoryService _service;
        private readonly IDegreeBL _bl;
        public DegreesController(RepositoryService service, IDegreeBL bl)
        {
            _service = service;
            _bl = bl;
        }

        // GET: Degrees
        public async Task<IActionResult> Index(int employeeId)
        {
            var degreesViewModel = _bl.FetchDegree(employeeId).ToList();
            await ViewEmployeeData(employeeId);
            return View(degreesViewModel);
        }

        // GET: Degrees/Create
        public IActionResult Create(int employeeId)
        {
            var numberOfDegrees = _bl.GetNumberOfDegrees(employeeId);
            if (numberOfDegrees >= MaxNumberOfDegrees)
            {
                TempData["ErrorMessage"] = "Number of degrees is max.";
                return RedirectToAction(nameof(Index), new { employeeId });
            }
            DropDownList(employeeId);
            return View();
        }

        // POST: Degrees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int employeeId, DegreeEditModel degreeEditModel)
        {
            if (!ModelState.IsValid)
            {
                DropDownList(employeeId);
                return View(degreeEditModel);
            }

            var isSucessCreate = await _bl.AddDegree(degreeEditModel);
            if(!isSucessCreate)
            {
                TempData["ErrorMessage"] = "An error occurred while creating the degree.";
                return View(degreeEditModel);
            }
            TempData["SuccessMessage"] = "Degree created successfully";
            return RedirectToAction(nameof(Index), new { employeeId });
        }

        // GET: Degrees/Edit/5
        public async Task<IActionResult> Edit(int? id, int employeeId)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var degree = await _bl.GetDegreeById(id);
            if (degree == null)
            {
                return NotFound();
            }

            var degreeEditModel = _bl.SetDegreeEditModel(degree);
            DropDownList(employeeId);
            return View(degreeEditModel);
        }

        // POST: Degrees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, int employeeId, DegreeEditModel degreeEditModel)
        {
            if (id != degreeEditModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                DropDownList(employeeId);
                return View(degreeEditModel);
            }

            var isSucessEdit = await _bl.EditDegree(degreeEditModel);
            if(!isSucessEdit)
            {
                TempData["ErrorMessage"] = "An error occurred while updating the degree.";
                return View(degreeEditModel);
            }
            TempData["SuccessMessage"] = "Degree updated successfully";
            return RedirectToAction(nameof(Index), new { employeeId = degreeEditModel.EmployeeId });
        }

        // GET: Degrees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var degree = await _bl.GetDegreeById(id);

            if (degree == null)
            {
                return NotFound();
            }

            var degreeViewModel = _bl.SetDegreeViewModelDelete(degree);
            return View(degreeViewModel);
        }

        // POST: Degrees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var degree = await _bl.GetDegreeById(id);
            if (degree != null)
            {
                var isSucessDelete = await _bl.DeleteDegree(degree);
                if (!isSucessDelete)
                {
                    TempData["ErrorMessage"] = "An error occurred while updating the degree.";
                    return RedirectToAction(nameof(Index), new { employeeId = degree!.EmployeeId });
                }
            }
            TempData["SuccessMessage"] = "Degree deleted successfully";
            return RedirectToAction(nameof(Index), new { employeeId = degree!.EmployeeId });
        }

        public void DropDownList(int employeeId)
        {
            ViewData["EmployeeId"] = employeeId;
            ViewData["ProvinceId"] = new SelectList(_service.GetProvinceDbset(), "Id", "Name");
        }

        public async Task ViewEmployeeData(int employeeId)
        {
            var employee = await _bl.GetEmployeeById(employeeId);
            ViewData["employeeId"] = employeeId;
            ViewData["employeeName"] = employee!.Name;
            ViewData["numberOfDegrees"] = employee.Degrees!.Count;
        }
    }
}

WebFormL1/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using WebFormL1.BusinessLogic;
using WebFormL1.EditModel;
using WebFormL1.Service;
using WebFormL1.ViewModel;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebFormL1.Constant;
using WebFormL1.Interface;
using WebFormL1.Utility;
using WebFormL1.Filters;

namespace WebFormL1.Controllers
{
    [ServiceFilter(typeof(SessionAuthorizeFilter))]
    public class EmployeesController : BaseController
    {
        private readonly IEmployeeBL _bl;
        private readonly RepositoryService _service;

        public EmployeesController(IEmployeeBL bl, RepositoryService service)
        {
            _bl = bl;
            _service = service;
        }

        // GET: Employees
        public IActionResult Index(int? page, int? size, string searchString = "")
        {
                int pageIndex = Validate.ValidatePageNumber(ref page); ;
                int pageSize = Validate.ValidatePageSize(ref size);
                ViewBag.size = GetPageSizeOptions(size);
                ViewBag.currentSize = size;
                var employeesViewModel = _bl.FetchEmployeePage(pageIndex, pageSize, searchString); 
                ViewData["searchString"] = searchString;
                return View(new StaticPagedList<EmployeeViewModel>(employeesViewModel.ViewModel!,
                                         pageIndex, pageSize, employeesViewModel.TotalPages));
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var employee = await _bl.GetEmployeeById(id);

            if (employee == null)
            {
                return NotFound();
            }

            var employeeViewModel = _bl.SetEmployeeViewModel(employee);
            return View(employeeViewModel);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            DropDownListView();
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeEditModel employeeEditModel)
        {
            if (!ModelState.IsValid)
            {
                DropDownListView();
                return View(employeeEditModel);
            }

            var isSucessCreate = await _bl.AddEmployee(employeeEditModel);
            if (!isSucessCreate)
            {
                TempData["ErrorMessage"] = "An error occurred while createing the employee.";
                return View(employeeEditModel);
            }
            TempData["SuccessMessage"] = "Employee created successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var employee = await _bl.GetEmployeeById(id);

            if (employee == null)
            {
                return NotFound();
            }

            var employeeEditModel = _bl.SetEmployeeEditModel(employee);
            DropDownListView();
            return View(employeeEditModel);
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EmployeeEditModel employeeEditModel)
        {
            if (id != employeeEditModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                DropDownListView();
                return View(employeeEditModel);
            }

            var isSucessEdit = await _bl.EditEmployee(employeeEditModel);
            if (!isSucessEdit)
            {
                TempData["ErrorMessage"] = "An error occurred while updating the employee.";
                return View(employeeEditModel);
            }

            TempData["SuccessMessage"] = "Employee updated successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var employee = await _bl.GetEmployeeById(id);

            if (employee == null)
            {
                return NotFound();
            }

            var employeeViewModel = _bl.SetEmployeeViewModel(employee);
            return View(employeeViewModel);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _bl.GetEmployeeByIdDelete(id);
            if (employee != null)
            {
                var isSuccessDelete = await _bl.DeleteEmployee(employee);
                if (!isSuccessDelete)
                {
                    TempData["ErrorMessage"] = "An error occurred while deleting the employee.";
                    return RedirectToAction(nameof(Index));
                }
                TempData["SuccessMessage"] = "Employee deleted successfully";
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
        public IActionResult ExportExcel(string searchString = "")
        {
            var employeesViewModel = _bl.GetModelExportData(searchString);

            ViewBag.exportSearchString = searchString;
            return View(employeesViewModel);
        }

        // POST: ExportExcel
        [HttpPost]
        public async Task<IActionResult> ExportExcel(List<int> employeeIdList)
        {
            if (employeeIdList == null || employeeIdList.Count == 0)
            {
                TempData["ErrorMessage"] = "Không có thông tin được chọn";
                return RedirectToAction(nameof(ExportExcel));
            }

            var streamData = await _bl.HandleDataToExportExcel(employeeIdList);
            var fileName = "employeeData.xlsx";
            return File(streamData.ToArray()
                , "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", fileName);
        }
        public IActionResult ImportExcel()
        {
            return View();
        }

        // POST: ImportExcel
        [HttpPost]
        public async Task<IActionResult> ImportExcel(IFormFile formFile)
        {
            if (_bl.IsInvalidFormFile(formFile))
            {
                TempData["ErrorMessage"] = "File trống hoặc sai định dạng";
                return View();
            }

            var importEmployees = _bl.GetListDataImport(formFile);
            if (importEmployees == null)
            {
                TempData["ErrorMessage"] = "Dữ liệu không hợp lệ";
                return View();
            }

            var validateImportData = ValidateImportEmployee(importEmployees);
            if (validateImportData != 0)
            {
                TempData["ErrorMessage"] = "Dữ liệu không hợp lệ";
                return View();
            }

            if (!await _bl.IsSuccessImport(importEmployees))
            {
                TempData["ErrorMessage"] = "Dữ liệu không hợp lệ";
                return View();
            }

            TempData["SuccessMessage"] = "Nhập dữ liệu từ Excel thành công";
            return RedirectToAction(nameof(Index));
        }
        public void DropDownListView()
        {
            ViewData["JobData"] = new SelectList(_service.GetJobDbset(), "Id", "JobName");
            ViewData["EthnicData"] = new SelectList(_service.GetEthnicDbset(), "Id", "EthnicName");
            ViewData["ProvinceData"] = new SelectList(_service.GetProvinceDbset(), "Id", "Name");
            ViewData["DistrictData"] = new SelectList(_service.GetDistrictDbset(), "Id", "Name");
            ViewData["CommuneData"] = new SelectList(_service.GetCommuneSet(), "Id", "Name");
        }
    }
}

WebFormL1/Views/Employees/Create.cshtml
@model WebFormL1.EditModel.EmployeeEditModel

@{
    ViewData["Title"] = "Create";
}

<h1>Thêm nhân viên</h1>
<hr />
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<div class="row">
    <div id="create-employee">
        <form asp-action="Create" class="create-employee-form" method="post">
            <div class="row">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group col-md-3">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="DateOfBirth" class="control-label"></label>
                    <input asp-for="DateOfBirth" class="form-control dobInput" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="EthnicId" class="control-label"></label>
                    <select asp-for="EthnicId" class="form-select" asp-items="ViewBag.EthnicData">
                        <option selected></option>
                    </select>
                    <span asp-validation-for="EthnicId" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="JobId" class="control-label"></label>
                    <select asp-for="JobId" class="form-select" asp-items="ViewBag.JobData">
                        <option selected></option>
                    </select>
                    <span asp-validation-for="JobId" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3 checkBoxInput">
                    <label asp-for="IdentifyCardNumber" class="control-label"></label>
                    <input asp-for="IdentifyCardNumber" class="form-control checkBoxText" required title="Vui lòng hoàn thành thông tin" />
                    <span asp-validation-for="IdentifyCardNumber" class="text-danger validTextCheckBox"></span>
                    <div>
                        <input class="form-check-input check" type="checkbox" value="" />
                        <label class="form-check-label" for="citizenIdCheck">
                            Không có CCCD
                        </label>
                    </div>
                </div>
                <div class="form-group col-md-3 checkBoxInput">
                    <label asp-for="PhoneNumber" class="control-label"></label>
                    <input asp-for="PhoneNumber" class="form-control checkBoxText" required title="Vui lòng hoàn thành thông tin" />
                    <span asp-validation-for="PhoneNumber" class="text-danger validTextCheckBox"></span>
                    <div>
                        <input class="form-check-input check" type="checkbox" value="" />
                        <label class="form-check-label" for="phoneCheck">
                            Không có SĐT
                        </label>
                    </div>
                </div>
            </div>

            <div class="row">
                <h5>Địa chỉ</h5>
                <div class="form-group col-md-3">
                    <label asp-for="ProvinceId" class="control-label"></label>
                    <select asp-for="ProvinceId" class="form-select" asp-items="ViewBag.ProvinceData" id="provinceId">
                        <option selected></option>
                    </select>
                    <span asp-validation-for="ProvinceId" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="DistrictId" class="control-label"></label>
                    <select asp-for="DistrictId" class="form-select" id="districtId">
                        <option></option>
                    </select>
                    <span asp-validation-for="DistrictId" class="text-danger"></span>
                </div>
                <div class="form-group col-md-3">
                    <label asp-for="CommuneId" class="control-label"></label>
                    <select asp-for="CommuneId" class="form-select" id="communeId">
                        <option></option>
                    </select>
                    <span asp-validation-for="CommuneId" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group mt-3">
                <input type="submit" value="Thêm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách nhân viên</a>
</div>



@section Scripts {
    <script>
        $('.checkBoxInput').each(function (index, element) {
            $(element).find('.check').click(function () {
                $(element).find('.validTextCheckBox').toggle();
                if ($(element).find('.check').prop('checked')) {
                    $(element).find('.checkBoxText').val('').attr('disabled', 'disabled').removeAttr('required');
                    return;
                }
                $(element).find('.checkBoxText').removeAttr('disabled').attr('required', 'required');
            });
        });

        $(document).ready(function () {
            getDistrictByProvinceId();
        })
        $("#provinceId").change(function () {
            getDistrictByProvinceId();
        });
        var getDistrictByProvinceId = function () {
            $.ajax(
                {
                    url: '@Url.Action("GetDistrictByProvince","Districts")',
                    type: 'GET',
                    data: {
                        provinceId: $('#provinceId').val(),
                    },
                    success: function (data) {
                        $('#districtId').html('');
                        $(data).each(
                            function (index, item) {
                                $('#districtId').append('<option value="' + item.id + '">' + item.name + '</option>')
                            }
                        );
                        $('#districtId').val($('#districtId option:first').val());
                        $('#districtId').change();
                    }
                }
            )
        }
        $(document).ready(function () {
            getCommuneByDistrictId();
        })
        $("#districtId").change(function () {
            getCommuneByDistrictId();
        });
        var getCommuneByDistrictId = function () {
            $.ajax(
                {
                    url: '@Url.Action("GetCommuneByDistrict","Communes")',
                    type: 'GET',
                    data: {
                        districtId: $('#districtId').val(),
                    },
                    success: function (data) {
                        $('#communeId').html('');
                        $(data).each(
                            function (index, item) {
                                $('#communeId').append('<option value="' + item.id + '">' + item.name + '</option>')
                            }
                        );
                    }
                }
            )
        }
    </script>
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebFormL1/Views/Employees/ImportExcel.cshtml
@{
    ViewData["Title"] = "Nhập Excel";
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<div class="container">
    <div class="page-header">
        <h1>Nhập thông tin nhân viên từ Excel</h1>
    </div>

    <div class="alert alert-info">
        Chỉ chấp nhận các định dạng file .xlsx, .xlsm
    </div>

    <form asp-action="ImportExcel" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label class="form-label">Chọn một file</label>
            <input class="form-control" type="file" name="formFile" accept=".xlsx, .xlsm" />
        </div>

        <div>
            <input type="submit" value="Nhập" class="btn btn-primary" /> |
            <a asp-action="Index">Danh sách nhân viên</a>
        </div>
    </form>
</div>

@if (ViewData["ImportError"] != null)
{
    <p class="text-danger mt-2 ms-2">
        @ViewData["ImportError"]
    </p>
}

WebFormL1/Views/Employees/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<WebFormL1.ViewModel.EmployeeViewModel>

@{
    ViewData["Title"] = "Home";
}

<h1>Danh sách nhân viên</h1>

<div class="row justify-content-between">
    <p class="col-3">
        <a asp-action="Create" class="btn btn-success">Thêm mới</a>
    </p>
    <p class="col-3">
        <a asp-action="ImportExcel" class="btn btn-outline-primary ">Nhập Excel</a>
        <a asp-action="ExportExcel" class="btn btn-outline-primary">Xuất Excel</a>
    </p>
</div>
<div class="position-absolute end-0 top-0">
    <!-- Search form with Bootstrap styles -->
    <form asp-action="Index" method="get" class="form-inline">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Tìm.." name="searchString" value="@ViewBag.searchString">
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">
                    <i class="fa fa-search" aria-hidden="true"></i> Tìm
                </button>
            </div>
        </div>
    </form>
</div>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].EthnicityName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].JobName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].IdentityCardNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].NumberOfDegrees)
            </th>
            <th>
                Attendance
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateOfBirth)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Age)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EthnicityName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdentityCardNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NumberOfDegrees)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AttendedSessions)/@Html.DisplayFor(modelItem => item.Sessions)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Sửa</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary btn-sm">Chi tiết</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm me-3">Xóa</a>
                    <a asp-controller="Degrees" asp-action="Index" asp-route-employeeId="@item.Id" class="btn btn-info btn-sm">Văn bằng</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div class="row">
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Html.BeginForm("Index", "Employees", FormMethod.Get))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
            </p>
            @Html.Hidden("searchString", (object)ViewBag.searchString)
        }
    </div>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
        Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
</div>
@{
    // Ensure page number is not less than or equal to 0
    var currentPage = Model.PageNumber <= 0 ? 1 : Model.PageNumber;

    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }
        if (request.Query[key].Count > 1)
        {
            foreach (var item in (string[])request.Query[key])
            {
                urlTemplate += "&" + key + "=" + item;
            }
        }
        else
        {
            urlTemplate += "&" + key + "=" + request.Query[key];
        }
    }

    var startIndex = Math.Max(currentPage - 5, 1);
    var finishIndex = Math.Min(currentPage + 5, Model.PageCount);
}

@if (Model.PageCount > 1)
{
    <ul class="pagination">
        @if (currentPage != startIndex)
        {
            <li class="page-item">
                <a class="page-link" title="1" href="@urlTemplate.Replace("{0}", "1")">Đầu</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", (currentPage - 1).ToString())">Trước</a>
            </li>
        }
        @for (var i = startIndex; i <= finishIndex; i++)
        {
            if (i == currentPage)
            {
                <li class="page-item active">
                    <a class="page-link" href="#">@i <span class="sr-only">(current)</span></a>
                </li>
            }
            else
            {
                <li class="page-item"><a class="page-link" title="Trang @i.ToString()" href="@urlTemplate.Replace("{0}", i.ToString())">@i</a></li>
            }
        }
        @if (currentPage != finishIndex)
        {
            <li class="page-item">
                <a class="page-link" title="@Model.PageCount.ToString()" href="@urlTemplate.Replace("{0}", (currentPage + 1).ToString())">Sau</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", Model.PageCount.ToString())">Cuối</a>
            </li>
        }
    </ul>
}