WebFormL1/Models/Commune.cs
using System.ComponentModel.DataAnnotations;
using WebFormL1.BusinessLogic;

namespace WebFormL1.Models
{
    public class Commune
    {
        public Commune()
        {
        }
        public Commune(int id, string name,string level,int districtId)
        {
            Id = id;
            Name = name;
            Level =level;
            DistrictId = districtId;
        }
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Level { get; set; }
        public int DistrictId { get; set; }
        public District? District { get; set; }
    }
}

WebFormL1/Controllers/CommunesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebFormL1.EditModel;
using WebFormL1.Interface;
using WebFormL1.Service;
using WebFormL1.Utility;
using WebFormL1.ViewModel;
using X.PagedList;

namespace WebFormL1.Controllers
{
    public class CommunesController : BaseController
    {
        private readonly RepositoryService _repos;

        private readonly ICommuneBL _bl;

        public CommunesController(ICommuneBL bl, RepositoryService repos)
        {
            _bl = bl;
            _repos = repos;
        }

        // GET: Districts
        public IActionResult Index(int? page,int ?size,string searchString = "")
        {
            int pageIndex = Validate.ValidatePageNumber(ref page);
            int pageSize = Validate.ValidatePageSize(ref size);
            ViewBag.size = GetPageSizeOptions(size);
            ViewBag.currentSize = size;
            var communesViewModel = _bl.FetchCommunePage(pageIndex, pageSize, searchString);
            ViewData["searchString"] = searchString;

            return View(new StaticPagedList<CommuneViewModel>(communesViewModel.ViewModel!,
                                     pageIndex, pageSize, communesViewModel.TotalPages));
        }


        // GET: Districts/Create
        public IActionResult Create()
        {
            DropDownList();
            return View();
        }

        // POST: Districts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CommuneEditModel communeEditModel)
        {
            if (!ModelState.IsValid)
            {
                DropDownList();
                return View(communeEditModel);
            }

            var isSucessCreate = await _bl.AddCommune(communeEditModel);
            if(!isSucessCreate)
            {
                TempData["ErrorMessage"] = "An error occurred while creating the communes.";
                return View(communeEditModel);
            }
            TempData["SuccessMessage"] = "Commune created successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Districts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var commune = await _bl.GetCommuneById(id);
            if (commune == null)
            {
                return NotFound();
            }

            var communeEditModel = new CommuneEditModel(commune!.Id, commune.Name!, commune.Level, commune.DistrictId,commune.District!.ProvinceId);
            DropDownList();

            return View(communeEditModel);

        }

        // POST: Districts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CommuneEditModel communeEditModel)
        {
            if (id != communeEditModel.Id)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                DropDownList();
                return View(communeEditModel);
            }
            var isSucessEdit = await _bl.EditCommune(communeEditModel);
            if(!isSucessEdit)
            {
                TempData["ErrorMessage"] = "An error occurred while creating the communes.";
                return View(communeEditModel);
            }
            TempData["SuccessMessage"] = "Commune updated successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Districts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var commune = await _bl.GetCommuneById(id);

            if (commune == null)
            {
                return NotFound();
            }

            var communeViewModel = new CommuneViewModel(commune.Id, commune.Name!, commune.District!.Name!,commune.District.Province!.Name, commune.Level);
            return View(communeViewModel);
        }

        // POST: Districts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commune = await _bl.GetCommuneById(id);
            if (commune == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var isSucessDelete = await _bl.DeleteCommune(commune);
            if(!isSucessDelete)
            {
                TempData["ErrorMessage"] = "An error occurred while creating the communes.";
                return RedirectToAction(nameof(Index));
            }
            TempData["SuccessMessage"] = "Commune deleted successfully";
            return RedirectToAction(nameof(Index));
        }
        public void DropDownList()
        {
            var levels = new List<SelectListItem>
            {
                new SelectListItem { Value = "Phường", Text = "Phường" },
                new SelectListItem { Value = "Xã", Text = "Xã" },
                new SelectListItem { Value = "Thị trấn", Text = "Thị trấn" }
            };
            ViewBag.Levels = levels;
            ViewData["ProvinceId"] = new SelectList(_repos.GetProvinceDbset(), "Id", "Name");
        }
        public JsonResult GetCommuneByDistrict(int districtId)
        {
            return Json(_bl.GetCommuneListByDistrict(districtId));
        }
    }
}

WebFormL1/Controllers/DistrictsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebFormL1.BusinessLogic;
using WebFormL1.EditModel;
using WebFormL1.ViewModel;
using WebFormL1.Service;
using X.PagedList;
using WebFormL1.Interface;
using WebFormL1.Constant;
using WebFormL1.Utility;

namespace WebFormL1.Controllers
{
    public class DistrictsController : BaseController
    {
        private readonly RepositoryService _repos;

        private readonly IDistrictBL _bl;

        public DistrictsController(IDistrictBL bl, RepositoryService repos)
        {
            _bl = bl;
            _repos = repos;
        }

        // GET: Districts
        public IActionResult Index(int? page,int? size,string searchString = "")
        {
            int pageIndex = Validate.ValidatePageNumber(ref page);
            int pageSize = Validate.ValidatePageSize(ref size);
            ViewBag.size = GetPageSizeOptions(size);
            ViewBag.currentSize = size;
            var districtsViewModel = _bl.FetchDistrictPage(pageIndex, pageSize,searchString);
            ViewData["searchString"] = searchString;

            return View(new StaticPagedList<DistrictViewModel>(districtsViewModel.ViewModel!,
                                     pageIndex, pageSize, districtsViewModel.TotalPages));
        }


        // GET: Districts/Create
        public IActionResult Create()
        {
            DropDownList();
            return View();
        }

        // POST: Districts/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Level,ProvinceId")] DistrictEditModel districtEditModel)
        {
            if (!ModelState.IsValid)
            {
                DropDownList();
                return View(districtEditModel);
            }

            var isSuccessCreate = await _bl.AddDistrict(districtEditModel);
            if(!isSuccessCreate)
            {
                TempData["ErrorMessage"] = "An error occurred while creating the districts.";
                return View(districtEditModel);
            }
            TempData["SuccessMessage"] = "District created successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Districts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var district = await _bl.GetDistrictById(id);

            if (district == null)
            {
                return NotFound();
            }

            var districtEditModel = new DistrictEditModel(district.Id, district.Name, district.Level, district.ProvinceId);
            DropDownList();

            return View(districtEditModel);

        }

        // POST: Districts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, DistrictEditModel districtEditModel)
        {
            if (id != districtEditModel.Id)
            {
                return NotFound();
            }
            if (!ModelState.IsValid)
            {
                DropDownList();
                return View(districtEditModel);
            }
            var isSuccessEdit = await _bl.EditDistrict(districtEditModel);
            if(!isSuccessEdit) 
            {
                TempData["ErrorMessage"] = "An error occurred while updating the district.";
                return View(districtEditModel);
            }
            TempData["SuccessMessage"] = "District updated successfully";
            return RedirectToAction(nameof(Index));
        }

        // GET: Districts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            var district = await _bl.GetDistrictById(id);

            if (district == null)
            {
                return NotFound();
            }

            var districtViewModel = new DistrictViewModel(district.Id, district.Name, district.Province!.Name, district.Level);
            return View(districtViewModel);
        }

        // POST: Districts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var district = await _bl.GetDistrictById(id);
            if (district == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var isSuccessDelete = await _bl.DeleteDistrict(district);
            if(!isSuccessDelete)
            {
                TempData["ErrorMessage"] = "An error occurred while deleting the district.";
                return RedirectToAction(nameof(Index));
            }
            TempData["SuccessMessage"] = "District deleted successfully";
            return RedirectToAction(nameof(Index));
        }
        public void DropDownList()
        {
            var levels = new List<SelectListItem>
            {
                new SelectListItem { Value = "Huyện", Text = "Huyện" },
                new SelectListItem { Value = "Thành Phố", Text = "Thành Phố" },
                new SelectListItem { Value = "Quận", Text = "Quận" }
            };
            ViewBag.Levels = levels;
            ViewData["ProvinceId"] = new SelectList(_repos.GetProvinceDbset(), "Id", "Name");
        }
        public JsonResult GetDistrictByProvince(int provinceId)
        {
            return Json(_bl.GetDistrictListByProvince(provinceId));
        }
    }


}

WebFormL1/Views/Communes/Create.cshtml
@model WebFormL1.EditModel.CommuneEditModel

@{
    ViewData["Title"] = "Create";
}
<h1>Thêm xã/phường</h1>
<hr />
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<div class="row">
    <div>
        <form asp-action="Create" class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-4">
                <label asp-for="ProvinceId" class="control-label"></label>
                <select asp-for="ProvinceId" class="form-control provinces" asp-items="ViewBag.ProvinceID" id="provinceId">
                    <option selected></option>
                </select>
                <span asp-validation-for="ProvinceId" class="text-danger"></span>
            </div>
            <div class="form-group col-4">
                <label asp-for="DistrictId" class="control-label"></label>
                <select asp-for="DistrictId" class="form-control" id="districtId">
                </select>
                <span asp-validation-for="DistrictId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Level" class="control-label"></label>
                <select asp-for="Level" asp-items="ViewBag.levels" class="form-control">
                    <option value="">Chọn cấp bậc</option>
                </select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group col-4">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Thêm" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách xã/phường</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function (){
            getDistrictByProvinceId();
        })
        $("#provinceId").change(function () {
            getDistrictByProvinceId();
        });
        var getDistrictByProvinceId = function(){
            $.ajax(
                {
                    url: '@Url.Action("GetDistrictByProvince","Districts")',
                    type: 'GET',
                    data: {
                        provinceId: $('#provinceId').val(),
                    },
                    success : function(data)
                    {
                        $('#districtId').html('');
                        $(data).each(
                            function(index,item){
                                $('#districtId').append('<option value="' + item.id +'">' + item.name + '</option>')
                            }
                        );
                    }
                }
            )
        }
    </script>

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebFormL1/Views/Communes/Delete.cshtml
@model WebFormL1.ViewModel.CommuneViewModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa thông tin</h1>

<h3>Bạn có chắc muốn xóa thông tin xã/phường này?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DistrictName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DistrictName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProvinceName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProvinceName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Danh sách xã/phường</a>
    </form>
</div>

WebFormL1/Views/Communes/Edit.cshtml
@model WebFormL1.EditModel.CommuneEditModel

<h1>Sửa thông tin nhân viên</h1>
<hr />
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}
<div>
    <div>
        <form asp-action="Edit" class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-4">
                <label asp-for="ProvinceId" class="control-label"></label>
                <select asp-for="ProvinceId" class="form-control" asp-items="ViewBag.ProvinceID" id="provinceId">
                    <option selected></option>
                </select>
                <span asp-validation-for="ProvinceId" class="text-danger"></span>
            </div>
            <div class="form-group col-4">
                <label asp-for="DistrictId" class="control-label"></label>
                <select asp-for="DistrictId" class="form-control" id="districtId">
                </select>
                <span asp-validation-for="DistrictId" class="text-danger"></span>
            </div>
            <div class="form-group col-md-4">
                <label asp-for="Level" class="control-label"></label>
                <select asp-for="Level" asp-items="ViewBag.levels" class="form-control">
                    <option value="">Chọn cấp bậc</option>
                </select>
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group col-4">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-4">
                <input type="submit" value="Lưu" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Danh sách xã/phường</a>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            getDistrictByProvinceId();
        })
        $("#provinceId").change(function () {
            getDistrictByProvinceId();
        });
        var getDistrictByProvinceId = function () {
            $.ajax(
                {
                    url: '@Url.Action("GetDistrictByProvince","Districts")',
                    type: 'GET',
                    data: {
                        provinceId: $('#provinceId').val(),
                    },
                    success: function (data) {
                        $('#districtId').html('');
                        $(data).each(
                            function (index, item) {
                                $('#districtId').append('<option value="' + item.id + '">' + item.name + '</option>')
                            }
                        );
                    }
                }
            )
        }
    </script>

    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

WebFormL1/Views/Communes/Index.cshtml
@using X.PagedList.Mvc.Core
@using X.PagedList

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<WebFormL1.ViewModel.CommuneViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Danh sách xã/phường</h1>

<p>
    <a asp-action="Create" class="btn btn-success">Thêm mới</a>
</p>
<div class="position-absolute end-0 top-0">
    <!-- Search form with Bootstrap styles -->
    <form asp-action="Index" method="get" class="form-inline">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Tìm.." name="searchString" value="@ViewBag.searchString">
            <div class="input-group-append">
                <button type="submit" class="btn btn-outline-secondary">
                    <i class="fa fa-search" aria-hidden="true"></i> Tìm
                </button>
            </div>
        </div>
    </form>
</div>
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">@TempData["SuccessMessage"]</div>
}
@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger">@TempData["ErrorMessage"]</div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].DistrictName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].ProvinceName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model[0].Level)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DistrictName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ProvinceName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Level)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary btn-sm">Sửa</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Xóa</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="row">
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6">
        @using (Html.BeginForm("Index", "Communes", FormMethod.Get))
        {
            <p>
                Kích thước trang: @Html.DropDownList("size", (List<SelectListItem>)ViewBag.size, new { @onchange = "this.form.submit();" })
            </p>
            @Html.Hidden("searchString", (object)ViewBag.searchString)
        }
    </div>
    <div class="col-md-6 col-lg-6 col-xs-6 col-sm-6 text-right">
        Trang: @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount
    </div>
</div>
@{
    var currentPage = Model.PageNumber <= 0 ? 1 : Model.PageNumber;
    var urlTemplate = Url.Action() + "?page={0}";
    var request = ViewContext.HttpContext.Request;
    foreach (var key in request.Query.Keys)
    {
        if (key == "page")
        {
            continue;
        }
        if (request.Query[key].Count > 1)
        {
            foreach (var item in (string[])request.Query[key])
            {
                urlTemplate += "&" + key + "=" + item;
            }
        }
        else
        {
            urlTemplate += "&" + key + "=" + request.Query[key];
        }
    }

    var startIndex = Math.Max(Model.PageNumber - 5, 1);
    var finishIndex = Math.Min(Model.PageNumber + 5, Model.PageCount);
}

@if (Model.PageCount > 1)
{

    <ul class="pagination">
        @if (Model.PageNumber != startIndex)
        {
            <li class="page-item">
                <a class="page-link" title="1" href="@urlTemplate.Replace("{0}", "1")">Đầu</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", (Model.PageNumber-1).ToString())">Trước</a>
            </li>
        }
        @for (var i = startIndex; i <= finishIndex; i++)
        {
            if (i == Model.PageNumber)
            {
                <li class="page-item active">
                    <a class="page-link" href="#">@i <span class="sr-only">(current)</span></a>
                </li>
            }
            else
            {
                <li class="page-item"><a class="page-link" title="Trang @i.ToString()" href="@urlTemplate.Replace("{0}", i.ToString())">@i</a></li>
            }
        }
        @if (Model.PageNumber != finishIndex)
        {
            <li class="page-item">
                <a class="page-link" title="@Model.PageCount.ToString()" href="@urlTemplate.Replace("{0}", (Model.PageNumber+1).ToString())">Sau</a>
            </li>
            <li class="page-item">
                <a class="page-link" href="@urlTemplate.Replace("{0}", Model.PageCount.ToString())">Cuối</a>
            </li>
        }
    </ul>
}